
language: java
deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: bookworm-marketplace
before_install:
  - chmod +x mvnw
notifications:
  slack: nc-aof7593:WkeDRLH5jZfuLgskTGoTeAtW
branches:
  only:
    - master
    - develop
